source "https://rubygems.org"

# GitHub Pages gem includes Jekyll and common plugins
gem "github-pages", group: :jekyll_plugins

# Additional gems not included in github-pages
gem "webrick", "~> 1.8"
